### PR TITLE
Anchor residue as VMD selection

### PR DESCRIPTION
**Pull request by maxscheurer**
@ryanmcgreevy, can you merge the branch if there are no conflicts with your upcoming commits, please?

### CODE REVIEW

**Comment by ryanmcgreevy** [comment]
Works for me, however do we really need to use VMD atomselection text here? Rosetta only uses a single residue for the anchor, so I would imagine the user will always be typing `-anchor "resid X"`. Can we not just have the input be a residue number (following VMD's/the PDB's numbering) and convert that as appropriate to the corresponding Rosetta number?

**Comment by maxscheurer** [comment]
No, because one may have multiple chains in the pdb. Then, the "residue" numbering needs to be used. I think it's more intuitive to specify a whole selection to make it simple. The code, as implemented, also works if more than one residue is specified. @trudack, what do you think?

**Comment by ryanmcgreevy** [comment]
Yep, sorry I updated my previous comment right after posting it. I just committed some changes to update the README and `abinitio` usage text. I think I will go ahead and merge.

**Comment by maxscheurer** [comment]
Sorry, didn't see the updated comment :D

**Pull request merged**
