### PR TITLE
Reconciling differences between latest tutorial version and git version

### PR DESCRIPTION
**Pull request by ryanmcgreevy**
I started working on the modelmaker wrapper a while back and then the tutorial package was updated later and I didn't realize it. The biggest issue was the _analyze_ command was not working correctly for insertion results, primarily because it was still trying to use Juan Perilla's cluster script.

The tutmm branch represents the latest code taken from the tutorial files merged with the _majority_ of the commits to github. This version has been tested to work with both examples in the README using Rosetta 3.8. In order to get everything to work, I had to reverse 2 of Max's changes.

1.  The 'robust find_selection' change was not working (it seemed to be cutting off too much of the residue number text).
2. The wildcard additions to the rosettaEXE variable. The wildcard was not getting processed correctly when running the insertion test case. Also, the use of the wildcard I was referring to was more encompassing, the idea being to remove the need to care about _any_ aspect of the OS you were on (i.e., it should be possible to call the rosetta commands you want by name and wildcard out _all_ of the 'macoslangrelease' or 'linuxgccrelease' identifiers. We can discuss this more elsewhere.

Max, please have a look at the diffs and also if possible, check out the tutmm branch and test it yourself. If everything appears okay, I will merge it back into master and we can continue working from there. Thanks!

### CODE REVIEW

**Comment by maxscheurer** [comment]
The "more robust" find_selection command is the only way to make Rosetta 3.8 run
on my machine in ab-initio termini folding...

I don't know why this is causing problems in the insertion folding.

Actually, you're using a variable `$end` in l. 189, which is never defined beforehand.
"end" ought to refer to the final character in a string, but this cannot be used
in an `expr` in TCL, as far as I understand it. That's why I tried to refactor it with
the "more robust" thingy.

Obviously, there are differences in residue range handling.
Could you test the ab-initio termini folding again with your fixed version on your machine using Rosetta 3.8?

**Comment by ryanmcgreevy** [comment]
You're right, the `$end` was a mistake, but it seems like it was working because the `range` command was just defaulting to returning the entire string.  Your code looks like it is cutting off the last digit of the resid, causing rosetta to complain. If I set the code to the following:

`return [list $out_spans $exclude_string $chain_config $constraint]`

then running the abinitio code for termini works on both rosetta3.7 and rosetta3.8. Could you try checking out this _tutmm_ branch and seeing if it works for you?

**Comment by maxscheurer** [comment]
On my machine (Linux), Rosetta 3.8 is complaining about the last character in the residue range
string in the XML file, i.e. a comma ("1-195," or sth like that). Can you check if the XML
on your machine also shows this comma? Maybe we can quickly talk about this issue on Skype later.

**Comment by ryanmcgreevy** [comment]
My XML file does not have a comma as the last character. I am testing this with the commands found in the README, using the files from the first section of the tutorial, and using this _tutmm_ branch of the code.

**Pull request merged**
